### ISSUE TITLE
crashes when opening first files

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imcreg#23]
Hey,

when starting `immucan-roi` and selecting the input folder this error directly appears:

```
(immucan-roi) immucan@IMLS-11J80-M01 ~ % immucan-roi                                                               
2022-01-27 16:30:01.694 python[8669:109218] -[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:01.694 python[8669:109218] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x7fc9935a41a0> exception=-[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:01.696 python[8669:109218] -[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:01.696 python[8669:109218] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x7fc9935a41a0> exception=-[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:02.473 python[8669:109218] -[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:02.473 python[8669:109218] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x7fc9935a41a0> exception=-[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/bin/immucan-roi", line 8, in <module>
    sys.exit(main())
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/immucan_roi/__main__.py", line 21, in main
    app.exec_dialog()
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napping/_napping_application.py", line 80, in exec_dialog
    dialog = self._create_dialog()
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/immucan_roi/_immucan_napping_application.py", line 49, in _create_dialog
    for source_img_file in dialog.source_img_path.iterdir():
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/pathlib.py", line 1160, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/immucan_volume/czi'
(immucan-roi) immucan@IMLS-11J80-M01 ~ % immucan-roi
2022-01-27 16:30:09.482 python[8678:109787] -[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:09.482 python[8678:109787] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x7f8517d91cd0> exception=-[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:09.483 python[8678:109787] -[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:09.483 python[8678:109787] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x7f8517d91cd0> exception=-[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:10.745 python[8678:109787] -[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
2022-01-27 16:30:10.745 python[8678:109787] Exception calling directoryDidChange: on delegate <QNSOpenSavePanelDelegate: 0x7f8517d91cd0> exception=-[NSNull length]: unrecognized selector sent to instance 0x7fff88aec000
/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:242: UserWarning: data shape (33089, 38573) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:242: UserWarning: data shape (33089, 38573) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:242: UserWarning: data shape (33089, 38573) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:242: UserWarning: data shape (33089, 38573) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:242: UserWarning: data shape (33089, 38573) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:242: UserWarning: data shape (33089, 38573) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:242: UserWarning: data shape (33089, 38573) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:242: UserWarning: data shape (33089, 38573) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/_vispy/layers/image.py:242: UserWarning: data shape (33089, 38573) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1774, in create_block_manager_from_arrays
    mgr = BlockManager(blocks, axes)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 914, in __init__
    self._verify_integrity()
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 921, in _verify_integrity
    raise construction_error(tot_items, block.shape[1:], self.axes)
ValueError: Shape of passed values is (999, 1), indices imply (0, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/bin/immucan-roi", line 8, in <module>
    sys.exit(main())
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/immucan_roi/__main__.py", line 21, in main
    app.exec_dialog()
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napping/_napping_application.py", line 133, in exec_dialog
    self.exec(app=app)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napping/_napping_application.py", line 40, in exec
    self._current_source_viewer = self._create_source_viewer(
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/immucan_roi/_immucan_napping_application.py", line 59, in _create_source_viewer
    source_viewer = super(
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napping/_napping_application.py", line 234, in _create_source_viewer
    return NappingViewer(img_file)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napping/qt/_napping_viewer.py", line 39, in __init__
    self._points_layer = self._create_points_layer()
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napping/qt/_napping_viewer.py", line 76, in _create_points_layer
    points_layer = self._viewer.add_points(**self._POINTS_LAYER_ARGS)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/components/viewer_model.py", line 4, in add_points
    import itertools
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/layers/points/points.py", line 352, in __init__
    self._feature_table = _FeatureTable.from_layer(
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/layers/utils/layer_utils.py", line 882, in from_layer
    features = _features_from_properties(
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/layers/utils/layer_utils.py", line 941, in _features_from_properties
    return _validate_features(properties, num_data=num_data)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/napari/layers/utils/layer_utils.py", line 916, in _validate_features
    return pd.DataFrame(data=features, index=index)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/pandas/core/frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/pandas/core/internals/construction.py", line 135, in arrays_to_mgr
    return create_block_manager_from_arrays(
  File "/Users/immucan/opt/anaconda3/envs/immucan-roi/lib/python3.9/site-packages/pandas/core/internals/managers.py", line 1776, in create_block_manager_from_arrays
    raise construction_error(len(arrays), arrays[0].shape, axes, e)
ValueError: Shape of passed values is (999, 1), indices imply (0, 1)
```

Working on macOS Catalina 10.15.7 and `immucan-roi` v0.1.0. Thaaaaaaaank you :)

**Comment by nilseling** [comment]
As discovered by @StefanosVoglis, downgrading `napari` to v0.4.12 fixes this. Closing for now.

**Comment by jwindhager** [comment]
This should be fixed with immucan-roi v0.2.0, could you please verify? Thanks

**Comment by jwindhager** [comment]
Closing due to inactivity

**Comment by StefanosVoglis** [comment]
Sorry for late reply: 

This problem still exists in my setting:

- napari 0.4.14
- immucan-roi-0.2.4.dev4+g2bd8449 
- napari-czifile2-0.2.6 
- napari-imc-0.6.4

```
(napari-env) C:\Users\Stefanos>immucan-roi
WARNING: QWindowsWindow::setGeometry: Unable to set geometry 853x633-451+316 (frame: 871x680-460+278) on QWidgetWindow/"_QtMainWindowClassWindow" on "\\.\DISPLAY2". Resulting geometry: 626x624-455+296 (frame: 644x671-464+258) margins: 9, 38, 9, 9 minimum size: 626x624 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=644,671 maxtrack=0,0)
C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\_vispy\layers\image.py:242: UserWarning: data shape (27612, 34925) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\_vispy\layers\image.py:242: UserWarning: data shape (27612, 34925) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\_vispy\layers\image.py:242: UserWarning: data shape (27612, 34925) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\_vispy\layers\image.py:242: UserWarning: data shape (27612, 34925) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\_vispy\layers\image.py:242: UserWarning: data shape (27612, 34925) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\_vispy\layers\image.py:242: UserWarning: data shape (27612, 34925) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\_vispy\layers\image.py:242: UserWarning: data shape (27612, 34925) exceeds GL_MAX_TEXTURE_SIZE 16384 in at least one axis and will be downsampled. Rendering is currently in 2D mode.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\pandas\core\internals\managers.py", line 1774, in create_block_manager_from_arrays
    mgr = BlockManager(blocks, axes)
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\pandas\core\internals\managers.py", line 914, in __init__
    self._verify_integrity()
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\pandas\core\internals\managers.py", line 921, in _verify_integrity
    raise construction_error(tot_items, block.shape[1:], self.axes)
ValueError: Shape of passed values is (999, 1), indices imply (0, 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\Scripts\immucan-roi.exe\__main__.py", line 7, in <module>
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\immucan_roi\__main__.py", line 21, in main
    app.exec_dialog()
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napping\_napping_application.py", line 133, in exec_dialog
    self.exec(app=app)
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napping\_napping_application.py", line 40, in exec
    self._current_source_viewer = self._create_source_viewer(
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\immucan_roi\_immucan_roi.py", line 91, in _create_source_viewer
    source_viewer = super(IMMUcanNappingApplication, self)._create_source_viewer(
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napping\_napping_application.py", line 234, in _create_source_viewer
    return NappingViewer(img_file)
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napping\qt\_napping_viewer.py", line 39, in __init__
    self._points_layer = self._create_points_layer()
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napping\qt\_napping_viewer.py", line 76, in _create_points_layer
    points_layer = self._viewer.add_points(**self._POINTS_LAYER_ARGS)
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\components\viewer_model.py", line 4, in add_points
    import itertools
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\layers\points\points.py", line 364, in __init__
    self._feature_table = _FeatureTable.from_layer(
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\layers\utils\layer_utils.py", line 882, in from_layer
    features = _features_from_properties(
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\layers\utils\layer_utils.py", line 941, in _features_from_properties
    return _validate_features(properties, num_data=num_data)
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\napari\layers\utils\layer_utils.py", line 916, in _validate_features
    return pd.DataFrame(data=features, index=index)
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\pandas\core\frame.py", line 614, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\pandas\core\internals\construction.py", line 464, in dict_to_mgr
    return arrays_to_mgr(
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\pandas\core\internals\construction.py", line 135, in arrays_to_mgr
    return create_block_manager_from_arrays(
  File "C:\Users\Stefanos\anaconda3\envs\napari-env\lib\site-packages\pandas\core\internals\managers.py", line 1776, in create_block_manager_from_arrays
    raise construction_error(len(arrays), arrays[0].shape, axes, e)
ValueError: Shape of passed values is (999, 1), indices imply (0, 1)
```

**Comment by jwindhager** [comment]
Should be fixed with more recent napari versions, please reopen if still a problem
